CREATE TABLE USER(
	iboard INT PRIMARY KEY AUTO_INCREMENT,
	id VARCHAR(20) NOT NULL,
	pw VARCHAR(20) NOT NULL,
	house VARCHAR(20) NOT NULL,
	u_name VARCHAR(20) NOT NULL,
	created_at DATETIME DEFAULT NOW()	
);
